### ISSUE TITLE
Provide diagnostic context

### ISSUE THREAD

**Issue by jhermann** [mahmoud/lithoxyl#1]
The examples you give in the README are not exactly equivalent, namely the `lithoxyl` one drops the user name. This is an improved variant:

    from lithoxyl import stderr_log

    def create_user(name):
        with stderr_log.critical('user creation', context=name, reraise=False) as r:
            success = _create_user()
            if not success:
                r.failure()

**Comment by mahmoud** [comment]
That's true! I've done a little to make the examples closer now. The README is a bit old, so now I just need to find a way to exemplify some of these newer, cooler features. :) Maybe I'll ping you for some feedback when I wrap a couple up (you can seen them on the async branch). Thanks for your attention to detail!
